name: Start AWS RDS Instance

on:
  workflow_dispatch:
    inputs:
      db_instance:
        description: "RDS Instance Identifier"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  start_rds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check RDS Status Before Starting
        run: |
          DB_INSTANCE_ID=${{ github.event.inputs.db_instance }}
          
          echo "Fetching current status of RDS instance: $DB_INSTANCE_ID..."
          STATUS=$(aws rds describe-db-instances --db-instance-identifier "$DB_INSTANCE_ID" --query 'DBInstances[0].DBInstanceStatus' --output text)
          echo "Current RDS Status: $STATUS"

          if [[ "$STATUS" == "available" ]]; then
            echo "RDS instance is already running. Skipping start command."
            exit 0
          fi

          if [[ "$STATUS" == "stopped" ]] || [[ "$STATUS" == "inaccessible-encryption-credentials-recoverable" ]] || [[ "$STATUS" == "incompatible-network" ]]; then
            echo "Starting RDS instance..."
            aws rds start-db-instance --db-instance-identifier "$DB_INSTANCE_ID"
            exit 0
          fi

          echo "Instance cannot be started because it is in an invalid state: $STATUS"
          exit 1
