name: Start AWS RDS Instance

on:
  workflow_dispatch:
    inputs:
      db_instance:
        description: "RDS Instance Identifier"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  start_rds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Start RDS Instance
        run: |
          DB_INSTANCE_ID=${{ github.event.inputs.db_instance }}
          echo "Starting RDS instance: $DB_INSTANCE_ID in us-east-1..."
          aws rds start-db-instance --db-instance-identifier "$DB_INSTANCE_ID" --region us-east-1

